#!/usr/bin/env bash
./build/bin/llama-server \
  -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_M \
  --fit on\
  --fit-target 128 \
  --fit-ctx 196000 \
  -t 16 \
  --n-cpu-moe 25 \
  -np 1 \
  --no-mmap \
  --spec-type ngram-mod,draft-mtp \
  --spec-draft-n-max 6 \
  --spec-draft-p-min 0.75 \
  -fa on \
  -ctk q8_0 \
  -ctv q8_0 \
  --kv-unified \
  --batch-size 4096 --ubatch-size 2048 --cache-ram -1 \
  --temp 0.6 --top-p 0.95 --top-k 20 \
  --min-p 0.0 --presence-penalty 0.0 --repeat-penalty 1.0 \
  --reasoning-budget -1 \
  --host 0.0.0.0 \
  --port 8033 \
  --jinja --chat-template-file ~/devops/qwen3.6-templates/frogger_chat_template.jinja --no-ui -lv 4